### ISSUE TITLE
Sensitive information included in the repo?

### ISSUE THREAD

**Issue by javixeneize** [nhsx/covid-19-app-configuration-public#1]
Hi

I have seen some information related to certificates and CA included in the repo - https://github.com/nhsx/covid-19-app-configuration-public/blob/master/android/common/src/main/kotlin/EnvironmentConfiguration.kt

Can you check if this is any sensitive information there?

Thanks

**Comment by paulchambers** [comment]
They are the fingerprints of the public keys of the root certificates that the application trusts. 

These are public information published by the certificate authorities

**Comment by javixeneize** [comment]
Fine then. Thanks for clarifying
